// <auto-generated />
using System;
using DisasterResourceFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisasterResourceFinder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250815183339_SeedResources")]
    partial class SeedResources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisasterResourceFinder.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPetFriendly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWheelchairAccessible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Capacity = 150,
                            City = "Toronto",
                            IsPetFriendly = false,
                            IsWheelchairAccessible = true,
                            LastUpdated = new DateTime(2025, 8, 15, 18, 33, 38, 819, DateTimeKind.Utc).AddTicks(5750),
                            Latitude = 43.653199999999998,
                            Longitude = -79.383200000000002,
                            Name = "Downtown Emergency Shelter",
                            OpeningHours = "24/7",
                            Phone = "416-555-1234",
                            PostalCode = "M5H 2N2",
                            Type = "Shelter",
                            WebsiteUrl = "http://torontoshelter.ca"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Bloor St W",
                            Capacity = 300,
                            City = "Toronto",
                            IsPetFriendly = true,
                            IsWheelchairAccessible = true,
                            LastUpdated = new DateTime(2025, 8, 15, 18, 33, 38, 819, DateTimeKind.Utc).AddTicks(5753),
                            Latitude = 43.664999999999999,
                            Longitude = -79.414000000000001,
                            Name = "Westside Food Bank",
                            OpeningHours = "Mon-Fri 9am–5pm",
                            Phone = "416-555-5678",
                            PostalCode = "M6G 1K9",
                            Type = "Food",
                            WebsiteUrl = "http://westsidefoodbank.org"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Queen St E",
                            Capacity = 100,
                            City = "Toronto",
                            IsPetFriendly = false,
                            IsWheelchairAccessible = true,
                            LastUpdated = new DateTime(2025, 8, 15, 18, 33, 38, 819, DateTimeKind.Utc).AddTicks(5755),
                            Latitude = 43.658999999999999,
                            Longitude = -79.346999999999994,
                            Name = "City Medical Aid Clinic",
                            OpeningHours = "Mon–Sat 8am–8pm",
                            Phone = "416-555-9012",
                            PostalCode = "M4M 1H3",
                            Type = "Medical",
                            WebsiteUrl = "http://citymedclinic.ca"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
